#Crear una imagen de Docker que contenga una instancia de MySQL versión 5.7. Puede ser utilizada para ejecutar contenedores en diferentes entornos. Al utilizar un Dockerfile, podemos personalizar las configuraciones que se necesiten

#imagen base que se utilizará como punto de partida para construir la nueva imagen
FROM mysql:8.0

#shell que se utilizará para ejecutar los comandos dentro del contenedor. En este caso, estamos utilizando Bash como shell.
SHELL ["/bin/bash", "-c"]

#Puerto
EXPOSE 3306
